dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql

notifications:
  email: false

env:
  - TEST_RUN="tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)"
  - TEST_RUN="tox -e lint"

before_install:
  - psql -c 'create user cheeseshop;' -U postgres
  - psql -c 'ALTER USER cheeseshop CREATEDB;' -U postgres

install:
  - pip install -U tox setuptools pbr
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install .

script: "$TEST_RUN"
