host: 0.0.0.0
port: 8080
base_uri: http://localhost

swift:
  auth_url: "https://mykeystone"
  project_id: "dd415aad6718969c035781106fe8cb45b82"
  region: "RegionOne"
  user_id: "94ed55eb98d4033bafa16345e0ddaa3056"
  password: ""
  replays_container: "replays"

sql:
  host: localhost
  port: 5432
  database: cheeseshop-test
  user: cheeseshop
  password: cheeseshop
