apiVersion: v1
kind: Service
metadata:
  name: static-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30001
    name: static-server
  selector:
    app: static-server
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
  - port: 9970
    protocol: TCP
    nodePort: 30000
    name: webapp
  selector:
    app: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
      - name: static-server
        image: registry.ng.bluemix.net/greghaynes/cheeseshop-static:latest
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: registry.ng.bluemix.net/greghaynes/cheeseshop:latest
        ports:
        - containerPort: 9970
